apiVersion: v1
kind: Service
metadata:
  name: {{ template "team-management.fullname" . }}
  labels:
    app: {{ template "team-management.name" . }}
    chart: {{ template "team-management.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "team-management.name" . }}
    release: {{ .Release.Name }}
