# Default values for team-management.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.dev.coresuite.com/team-management
  tag: auto-filled-by-pipeline
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  httpPort: 8080

annotations:
  prometheus.io/scrape-job: "kubernetes-common-pods"
  prometheus.io/path: "/portal/metrics"
  prometheus.io/port: "8080"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
